name: Trigger lint format

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, review_requested ]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Lint Bot
    uses: unifyai/workflows/.github/workflows/pr-lint-bot.yml@automatic-lint-pr
    secrets: inherit